### ISSUE TITLE
Encoder model is using training=False

### ISSUE THREAD

**Issue by ksachdeva** [tanjatang/DCENet#1]
Hi,

First, thank you for the nicely written paper and for publishing the source code as well.

I was browsing through your code and noticed this -

https://github.com/tanjatang/DCENet/blob/451b8d581d486fced3428fcab8287a312feffece/scripts/self_attention_layer.py#L111

Based on my understanding, because of this hardcode training=False, it seems that dropouts in TransformerBlock layer will not happen even during training.

May be intentional but just wanted to point it out in case it is a typo

Regards & thanks
Kapil

**Comment by tanjatang** [comment]
Hi Kapil,

thanks for your comments. That's correct. The dropouts do not behave during training. Thanks for pointing it out. 

Best regards,
Xuejiao Tang
