### ISSUE TITLE
Question - Trajectory Ranking

### ISSUE THREAD

**Issue by ksachdeva** [tanjatang/DCENet#2]
Hi,

I like your take on ranking the trajectories. I believe it is important and have not seen anyone try to solve it before. That said, I am not 100% sure if I have understood it properly and hence few questions.

**Question 1**

In the paper, you state that you follow graves (https://arxiv.org/pdf/1308.0850.pdf), to come up with the PDF

![image](https://user-images.githubusercontent.com/127006/100261873-ffa64100-2f10-11eb-8919-b93cdf03a66c.png)

I then read the referenced paper of Alex Graves and to me, it seems that he is suggesting to use Mixture Density Networks to learn the distribution. Based on that I would have thought there will be an MDN layer present after the decoder. 

In the source code, it seems that you take the empirical mean of the predicted positions for an agent, and then that is used to create the PDF.

Am sure I am missing something fundamental here. Would appreciate it if you could educate.

**Question 2**

In your implementation, before you rank the trajectories, you bring the predicted trajectories to the original coordinate system by adding the last observation.

I was wondering if there is any downside to ranking the trajectories before bringing it them original coordinate. The reason I am thinking in this direction is that if there is no downside then it could save some computation time. For e.g. you could rank the trajectory and find the most likely one and then bring only this most likely one to the original coordinate system. This way addition of the last observation to the normalized trajectory is to be done on 1 trajectory per agent instead of 25 trajectories per agent. The same applies to the cumsum operation etc

##

Thanks in advance.

Regards & thanks
Kapil

**Comment by haohao11** [comment]
Hi Kapil,

Thank you very much for your comments and both of your questions are very valuable. 

Question 1:
We assume that the predicted positions form a bivariate gaussian distribution with one component. Hence, we used the empirical mean to calculate the PDF function. As you pointed out that the predictions could be multi-modality (like the original paper), having multiple components. In this case, I agree that it is more interesting to have a MDN layer. I appreciate that you give us a very good insight and we will investigate into this direction. 

Question 2
This is really a very good point. We will experiment this idea and see if this setting maintains the performance. 


Best regards,
Hao

**Comment by haohao11** [comment]
> Hi,
> 
> I like your take on ranking the trajectories. I believe it is important and have not seen anyone try to solve it before. That said, I am not 100% sure if I have understood it properly and hence few questions.
> 
> **Question 1**
> 
> In the paper, you state that you follow graves (https://arxiv.org/pdf/1308.0850.pdf), to come up with the PDF
> 
> ![image](https://user-images.githubusercontent.com/127006/100261873-ffa64100-2f10-11eb-8919-b93cdf03a66c.png)
> 
> I then read the referenced paper of Alex Graves and to me, it seems that he is suggesting to use Mixture Density Networks to learn the distribution. Based on that I would have thought there will be an MDN layer present after the decoder.
> 
> In the source code, it seems that you take the empirical mean of the predicted positions for an agent, and then that is used to create the PDF.
> 
> Am sure I am missing something fundamental here. Would appreciate it if you could educate.
> 
> **Question 2**
> 
> In your implementation, before you rank the trajectories, you bring the predicted trajectories to the original coordinate system by adding the last observation.
> 
> I was wondering if there is any downside to ranking the trajectories before bringing it them original coordinate. The reason I am thinking in this direction is that if there is no downside then it could save some computation time. For e.g. you could rank the trajectory and find the most likely one and then bring only this most likely one to the original coordinate system. This way addition of the last observation to the normalized trajectory is to be done on 1 trajectory per agent instead of 25 trajectories per agent. The same applies to the cumsum operation etc
> 
> Thanks in advance.
> 
> Regards & thanks
> Kapil


Hi Kapil,

Thank you very much for your comments and both of your questions are very valuable.

Question 1:
We assume that the predicted positions form a bivariate gaussian distribution with one component. Hence, we used the empirical mean to calculate the PDF function. As you pointed out that the predictions could be multi-modality (like the original paper), having multiple components. In this case, I agree that it is more interesting to have a MDN layer. I appreciate that you give us a very good insight and we will investigate into this direction.

Question 2
This is really a very good point. We will experiment this idea and see if this setting maintains the performance.

Best regards,
Hao

**Comment by ksachdeva** [comment]
Thanks, @haohao11 . Much appreciated the quick response and this good work.
