### ISSUE TITLE
How to understand the implement of the KL_loss?

### ISSUE THREAD

**Issue by Miaowaaaa** [tanjatang/DCENet#3]
Hello, it seems difficult to understand the calculation of the KL_loss for me. Can someone give me a few tips or references?
https://github.com/tanjatang/DCENet/blob/4e96eb34ef50684f27523f914edba117bbfce16b/scripts/DCENet.py#L171

**Comment by haohao11** [comment]
> Hello, it seems difficult to understand the calculation of the KL_loss for me. Can someone give me a few tips or references?
> https://github.com/tanjatang/DCENet/blob/4e96eb34ef50684f27523f914edba117bbfce16b/scripts/DCENet.py#L171

The KL_loss measures the errors between the distribution of the latent variables z and a Gaussian distribution. In other words, it tries to push the latent variables to be a Gaussian distribution, and it acts as the regularizer of the overall loss function. More theory can be found in the tutorial of https://arxiv.org/abs/1606.05908
