### ISSUE TITLE
Results of using pretrained model named best.hdf5

### ISSUE THREAD

**Issue by laurelyi2020** [tanjatang/DCENet#4]
Hello,
when applying the pretrained model best.hdf5, the test performance of bookstore-3 is shown as below:
![image](https://user-images.githubusercontent.com/66272899/119229110-f22ce500-bb48-11eb-838b-791aa3374bee.png)
it doesn't look like the one in the paper, all the prediction lines are just straight, I am wondering about it, could you please give me some advice on how it's happening? Thx and wish for you reply.

**Comment by haohao11** [comment]
Hi, thank you very much for the question. One can also play around with the hyper-parameters --num_pred and --beta to get more divergent multi-path predictions.
